export const POINTS=50;
export const FIELDS=[
 ['title','Название задачи','Например: Учёт заказов для ателье'],
 ['context','Контекст: что происходит сейчас','Как устроен текущий процесс?'],
 ['need','Потребность: что нужно изменить','Какую проблему необходимо решить?'],
 ['users','Пользователи','Кто будет пользоваться решением?'],
 ['userScenario','Сценарий использования','Что пользователь должен сделать?'],
 ['data','Данные и материалы','Какие данные, примеры или источники доступны?'],
 ['dataFormat','Формат данных','Таблица, CSV, документы, API…'],
 ['dataAccess','Порядок доступа','Когда и как команда получит материалы?'],
 ['result','Ожидаемый результат','Какой конкретный результат должна передать команда?'],
 ['resultFormat','Формат передачи результата','Прототип, исходный код, отчёт…'],
 ['criteria','Проверяемые критерии успеха','Числовые показатели или проверяемые условия'],
 ['acceptance','Порядок приёмки','Кто, как и на чём проверит результат?'],
 ['constraints','Ограничения','Технологии, доступы, бюджет или другие границы'],
 ['duration','Срок выполнения проекта','После выбора команды, например: 3 недели'],
 ['contact','Публичный контакт по задаче','Рабочая почта или телефон'],
 ['consultation','Формат консультаций','Например: онлайн-встреча по вторникам'],
 ['feedback','Порядок обратной связи','Кто отвечает и как быстро?']
];
export const EMPTY=Object.fromEntries(FIELDS.map(([k])=>[k,'']));
const excluded=/^(?:не\s+(?:указано|известно|знаю|решено|определено)|нет данных|позже|потом|тест|test|todo|tbd|n\/?a|none|null|undefined|нет|да|123|пример|уточняется|не применимо|заглушка)[.!…\s]*$/iu;
export const meaningful=x=>typeof x==='string'&&/[\p{L}\p{N}]/u.test(x.trim())&&!excluded.test(x.trim());
export const validContact=x=>meaningful(x)&&(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x.trim())||/^\+?[\d\s()\-]{10,20}$/.test(x.trim()));
export const safeURL=x=>{if(typeof x!=='string'||(!/^https?:\/\//i.test(x)&&x!=='./prototype.html'))return null;try{const u=new URL(x,globalThis.location?.href||'https://qadam.example');return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}};
const measured=x=>meaningful(x)&&(/\d|кажд|все\b|всех|без\s+потерь|не\s+(?:теряет|теряются)|успешно|возможность|отображает|сохраняет|создаёт|создает|экспорт|фильтр|уведомл|автоматич/iu.test(x));
export const RUBRIC=[
 {label:'Контекст и потребность',max:20,parts:[['context',10,'Опишите текущий процесс'],['need',10,'Уточните потребность']]},
 {label:'Данные и материалы',max:20,parts:[['data',10,'Укажите источники данных'],['dataFormat',5,'Уточните формат материалов'],['dataAccess',5,'Опишите порядок доступа']]},
 {label:'Ожидаемый результат',max:15,parts:[['result',10,'Опишите результат работы'],['resultFormat',5,'Укажите формат передачи']]},
 {label:'Критерии успеха',max:15,parts:[['criteria',10,'Добавьте проверяемый критерий',measured],['acceptance',5,'Опишите порядок приёмки']]},
 {label:'Ограничения',max:10,parts:[['constraints',5,'Укажите ограничения'],['duration',5,'Уточните срок проекта']]},
 {label:'Пользователи',max:10,parts:[['users',5,'Назовите пользователей'],['userScenario',5,'Опишите их сценарий']]},
 {label:'Связь с бизнесом',max:10,parts:[['contact',4,'Укажите корректный контакт',validContact],['consultation',3,'Уточните формат консультаций'],['feedback',3,'Опишите порядок обратной связи']]}
];
export function readiness(n){return n<40?{key:'draft',name:'Требует уточнения',short:'Черновик'}:n<70?{key:'working',name:'Рабочая',short:'Рабочая'}:n<90?{key:'ready',name:'Готовая',short:'Готовая'}:{key:'priority',name:'Приоритетная',short:'Приоритетная'};}
export function score(fields,confirmed=true){const categories=RUBRIC.map(c=>{const parts=c.parts.map(([key,max,hint,check=meaningful])=>({key,max,hint,earned:confirmed&&check(fields[key]||'')?max:0}));return {...c,parts,earned:parts.reduce((s,p)=>s+p.earned,0)};});const total=categories.reduce((s,c)=>s+c.earned,0);return {total,level:readiness(total),categories,missing:categories.flatMap(c=>c.parts.filter(p=>!p.earned))};}
export function catalog(tasks,filters={}){return tasks.filter(t=>t.published).filter(t=>!filters.q||`${t.fields.title} ${t.fields.context} ${t.company}`.toLowerCase().includes(filters.q.toLowerCase())).filter(t=>!filters.topic||t.topic===filters.topic).filter(t=>!filters.industry||t.industry===filters.industry).filter(t=>!filters.level||readiness(score(t.fields,t.confirmed).total).key===filters.level).filter(t=>!filters.open||isOpen(t)).sort((a,b)=>score(b.fields,b.confirmed).total-score(a.fields,a.confirmed).total||a.id.localeCompare(b.id));}
export const isOpen=(t,now=Date.now())=>!t.deadline||new Date(t.deadline).getTime()>now;
export function questionSet(fields={}){const qs=FIELDS.filter(([k])=>k!=='title'&&!meaningful(fields[k])).map(([field,label,question])=>({field,label,question}));const extras=[['acceptance','Приёмка','Какие пограничные случаи нужно проверить при приёмке?'],['dataAccess','Доступ','Нужно ли обезличить материалы перед передачей?'],['feedback','Обратная связь','Как действовать, если бизнес не может ответить вовремя?']];for(const [field,label,question]of extras){if(qs.length>=3)break;qs.push({field,label,question});}return qs;}
export function extractFacts(raw){
 const fields={...EMPTY,context:raw.trim()};
 const chunks=raw.trim().split(/(?<=[.!?])\s+|\n+/u).filter(Boolean);
 const patterns={need:/(?:хотим|нужно|необходимо|требуется|нужен|нужна|цель\s*[:—-])/iu,users:/(?:пользователи\s*[:—-]|пользоваться\s+будут|решение\s+для)/iu,userScenario:/(?:сценарий\s*[:—-])/iu,data:/(?:есть\s+(?:данные|таблиц|csv|выгрузк|справочник|pdf)|имеется|доступны\s+(?:данные|материал)|источник\s*[:—-])/iu,dataFormat:/\b(?:csv|pdf|json|xlsx|api)\b|формат\s+данных/iu,dataAccess:/(?:доступ\s*[:—-]|передадим|предоставим)/iu,result:/(?:результат\s*[:—-]|на\s+выходе)/iu,resultFormat:/(?:формат\s+(?:передачи|результата)\s*[:—-])/iu,criteria:/(?:критери[ийя]\s*[:—-]|успех\s*[:—-]|не\s+более\s+\d|за\s+\d+\s+секунд)/iu,acceptance:/(?:приёмка|приемка|проверяет|проверим)/iu,constraints:/(?:ограничени[ея]\s*[:—-]|без\s+платных|только\s+обезличенн|нельзя)/iu,duration:/(?:срок\s*[:—-]|за\s+\d+\s+(?:недел|дн))/iu,consultation:/(?:консультаци|встреч[аи]\s+(?:по|кажд))/iu,feedback:/(?:отвечает\s+в\s+течение|обратная\s+связь\s*[:—-])/iu};
 for(const[k,pattern]of Object.entries(patterns)){const found=chunks.filter(x=>pattern.test(x));if(found.length)fields[k]=found.join(' ');}
 const mail=raw.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);if(mail)fields.contact=mail[0];
 return fields;
}
export const AI_PROMPT=`Ты помогаешь бизнесу уточнять задачу. Используй только факты из raw и fields. Не добавляй факты, сроки, имена или контакты. Не выбирай команды. Верни JSON: {"questions":[{"field":"ключ поля","label":"раздел","question":"вопрос"}],"fields":{...}}. Нужно минимум 3 уместных вопроса по отсутствующим сведениям; для заполненной карточки уточняй неоднозначности и приёмку. Не публикуй результат. Неизвестные поля — пустые строки. Рекомендации выделяй отдельно и требуй подтверждения.`;
export function validateAI(value){if(!value||!Array.isArray(value.questions)||value.questions.length<3||!value.fields||typeof value.fields!=='object'||Array.isArray(value.fields)||!value.questions.every(q=>FIELDS.some(([k])=>k===q.field)&&typeof q.question==='string'&&q.question.trim().length>5)||!Object.entries(value.fields).every(([k,v])=>FIELDS.some(([f])=>f===k)&&typeof v==='string'))throw new Error('Некорректный или неполный ответ AI');return value;}
export async function analyze(raw,mode='demo',known={}){const fields={...extractFacts(raw),...Object.fromEntries(Object.entries(known).filter(([,v])=>meaningful(v)))};try{const request=new Promise((resolve,reject)=>setTimeout(()=>{if(mode==='unavailable')reject(new Error('Сервис недоступен'));else if(mode==='invalid')resolve({questions:[]});else if(mode==='timeout')return;else resolve({questions:questionSet(fields),fields});},mode==='demo'?350:100));let timer;const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('Время ожидания истекло')),800);});let result;try{result=await Promise.race([request,timeout]);}finally{clearTimeout(timer);}return {...validateAI(result),fallback:false};}catch(e){return {fields,questions:questionSet(fields),fallback:true,error:e.message};}}
export function upsertProposal(state,actor,taskId,input,now=Date.now()){if(actor.kind!=='team')throw new Error('Переключитесь на профиль команды');const task=state.tasks.find(t=>t.id===taskId);if(!task?.published)throw new Error('Задача не опубликована');if(!isOpen(task,now))throw new Error('Приём предложений завершён');for(const k of ['idea','plan','duration'])if(!meaningful(input[k]))throw new Error('Заполните идею, план и срок');if(!input.link||!safeURL(input.link))throw new Error('Добавьте ссылку http или https на прототип');const old=state.proposals.find(p=>p.taskId===taskId&&p.teamId===actor.id);if(old&&old.status!=='review')throw new Error('Решение уже принято. Обсудите изменения с бизнесом');if(old){Object.assign(old,input,{updatedAt:now});return old;}const p={id:'p-'+crypto.randomUUID(),taskId,teamId:actor.id,alias:state.proposals.filter(p=>p.taskId===taskId).length+1,...input,status:'review',createdAt:now,stage:null};state.proposals.push(p);return p;}
export function decide(state,actor,id,status){const p=state.proposals.find(p=>p.id===id),t=state.tasks.find(t=>t.id===p?.taskId);if(actor.kind!=='business'||t?.ownerId!==actor.id)throw new Error('Решение принимает владелец задачи');if(!['selected','rejected','review'].includes(status))throw new Error('Неизвестное решение');if(p.stage&&(p.stage.submitted||p.stage.approved)&&status!=='selected')throw new Error('После передачи результата выбор закреплён');p.status=status;if(status==='selected'&&!p.stage)p.stage={expected:t.fields.result||'Согласованный прототип решения',points:POINTS,submitted:false,approved:false,notes:'',link:''};return p;}
export function submitStage(state,actor,id,notes,link){const p=state.proposals.find(p=>p.id===id);if(actor.kind!=='team'||p?.teamId!==actor.id||p.status!=='selected')throw new Error('Результат отправляет выбранная команда');if(p.stage.approved)throw new Error('Этап уже подтверждён');if(!meaningful(notes)||!safeURL(link)||!link)throw new Error('Добавьте описание и корректную ссылку');Object.assign(p.stage,{notes,link,submitted:true});}
export function approveStage(state,actor,id){const p=state.proposals.find(p=>p.id===id),t=state.tasks.find(t=>t.id===p?.taskId);if(actor.kind!=='business'||t?.ownerId!==actor.id)throw new Error('Этап подтверждает владелец задачи');if(p.status!=='selected'||!p.stage?.submitted)throw new Error('Сначала команда должна отправить результат');if(p.stage.approved||state.ledger.some(x=>x.proposalId===id))return false;p.stage.approved=true;state.ledger.push({proposalId:id,teamId:p.teamId,points:POINTS,at:Date.now()});return true;}
export function teamProgress(state,id){const points=state.ledger.filter(l=>l.teamId===id).reduce((s,l)=>s+l.points,0);return {points,status:points<50?'Новичок':points<150?'Практик':points<300?'Опытный участник':'Продвинутый участник',next:points<50?50:points<150?150:points<300?300:null,proposals:new Set(state.proposals.filter(p=>p.teamId===id).map(p=>p.taskId)).size,results:state.ledger.filter(p=>p.teamId===id).length};}
