import test from 'node:test';
import assert from 'node:assert/strict';
import {seed} from '../dist/data.js';
const events={},tools=[],nodes=new Map();
for(const id of ['#app','#toast','#modal-root'])nodes.set(id,{innerHTML:'',textContent:'',classList:{add(){},remove(){}}});
let saved=JSON.stringify(seed());
globalThis.localStorage={getItem:()=>saved,setItem:(k,v)=>{saved=v}};
globalThis.location={hash:'#/catalog',href:'https://qadam.example/'};
globalThis.window={addEventListener:(n,f)=>{events[n]=f},scrollTo(){}};
globalThis.document={querySelector:s=>nodes.get(s)||null,querySelectorAll:()=>[],addEventListener(){},modelContext:{registerTool:t=>tools.push(t)}};
await import('../dist/app.js');
function renderRoute(route,data=seed()){location.hash=route;events.storage({key:'qadam-mvp-v1',newValue:JSON.stringify(data)});return nodes.get('#app').innerHTML;}
test('HTML всех основных экранов формируется без ошибок',()=>{for(const route of ['#/catalog','#/task/task1','#/my-tasks','#/proposals','#/profile','#/guide','#/create']){const html=renderRoute(route);assert.ok(html.includes('<main'));assert.ok(!html.includes('Не удалось открыть страницу'));assert.ok(!html.includes('undefined'));}const s=seed();s.actorId='t1';for(const route of ['#/task/task1','#/proposals','#/profile'])assert.ok(!renderRoute(route,s).includes('Не удалось открыть страницу'));});
test('Конструктор: три экрана и сохранённые значения',()=>{const s=seed();s.wizard={step:1,raw:'Описание с <тегом>',fields:{...s.tasks[0].fields},answers:{},questions:[{field:'need',question:'Какую проблему решаем?'},{field:'users',question:'Кто будет пользоваться?'},{field:'criteria',question:'Как проверим результат?'}],topic:'Веб-разработка',industry:'Услуги',deadline:'',reward:'',rewardTerms:''};assert.ok(renderRoute('#/create',s).includes('Описание с &lt;тегом&gt;'));s.wizard.step=2;assert.ok(renderRoute('#/create',s).includes('3 вопросов'));s.wizard.step=3;const html=renderRoute('#/create',s);assert.ok(html.includes('name="confirmed" type="checkbox" required'));assert.ok(html.includes('Подтвердить и опубликовать'));assert.ok(!html.includes('Не удалось открыть страницу'));});
test('До выбора профиль скрыт в списке предложений; после выбора раскрыт',()=>{const s=seed();let html=renderRoute('#/proposals',s).split('<main class="content">')[1];assert.ok(html.includes('Команда №001'));assert.ok(!html.includes('Data Nomads'));assert.ok(!html.includes('Pixel Union'));s.proposals[0].status='selected';s.proposals[0].stage={expected:'Прототип',points:50,submitted:false,approved:false};html=renderRoute('#/proposals',s).split('<main class="content">')[1];assert.ok(html.includes('Data Nomads'));assert.ok(!html.includes('Pixel Union'));});
test('Содержимое пользовательских полей экранируется',()=>{const s=seed();s.tasks[0].fields.title='<img src=x onerror=alert(1)>';s.proposals[0].idea='<script>alert(1)</script>';let html=renderRoute('#/task/task1',s);assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img src=x'));assert.ok(html.includes('&lt;script&gt;'));});
test('WebMCP mock: имена, схема, чтение и навигация с валидацией',()=>{renderRoute('#/catalog');assert.deepEqual(tools.map(t=>t.name),['list_published_tasks','open_task']);assert.equal(tools[0].annotations.readOnlyHint,true);assert.equal(tools[0].execute({}).length,5);assert.throws(()=>tools[0].execute({q:'unknown'}));assert.deepEqual(tools[1].execute({taskId:'task1'}),{taskId:'task1',view:'task'});assert.equal(location.hash,'/task/task1');assert.ok(nodes.get('#app').innerHTML.includes('Заказы под контролем'));assert.throws(()=>tools[1].execute({taskId:'missing'}));});
