"""initial relational schema

Revision ID: 0001
Revises:
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "moderation_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("ai_source", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_type", "entity_id", name="uq_moderation_entity"),
    )
    with op.batch_alter_table("moderation_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_moderation_items_status"), ["status"], unique=False
        )

    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.CheckConstraint("role IN ('STUDENT','COMPANY','ADMIN')"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("industry", sa.String(length=120), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("telegram", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "demo_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_table(
        "student_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=180), nullable=False),
        sa.Column("university", sa.String(length=180), nullable=False),
        sa.Column("specialization", sa.String(length=180), nullable=False),
        sa.Column("course", sa.Integer(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("interests", sa.JSON(), nullable=False),
        sa.Column("github_url", sa.String(length=500), nullable=False),
        sa.Column("portfolio_url", sa.String(length=500), nullable=False),
        sa.Column("total_points", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("total_points >= 0"),
        sa.ForeignKeyConstraint(
            ["id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "problems",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column("need", sa.Text(), nullable=False),
        sa.Column("users", sa.Text(), nullable=False),
        sa.Column("available_data", sa.Text(), nullable=False),
        sa.Column("constraints", sa.Text(), nullable=False),
        sa.Column("expected_result", sa.Text(), nullable=False),
        sa.Column("success_criteria", sa.Text(), nullable=False),
        sa.Column("business_contact", sa.Text(), nullable=False),
        sa.Column("interaction_format", sa.Text(), nullable=False),
        sa.Column("industry", sa.String(length=120), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("quality_score", sa.Integer(), nullable=False),
        sa.Column("ai_source", sa.String(length=30), nullable=False),
        sa.Column("winner_submission_id", sa.String(length=36), nullable=True),
        sa.Column("company_score", sa.Integer(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("hidden", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('DRAFT','PUBLISHED','CLOSED')"),
        sa.CheckConstraint("company_score IS NULL OR company_score BETWEEN 0 AND 100"),
        sa.CheckConstraint("quality_score BETWEEN 0 AND 100"),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_submission_id"],
            ["submissions.id"],
            name="fk_problem_winner",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("problems", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_problems_company_id"), ["company_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_problems_deadline"), ["deadline"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_problems_quality_score"), ["quality_score"], unique=False
        )

    op.create_table(
        "team_members",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "student_id"),
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("problem_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("hidden", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_comments_problem_id"), ["problem_id"], unique=False
        )

    op.create_table(
        "problem_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("problem_id", sa.Integer(), nullable=False),
        sa.Column("changed_fields", sa.JSON(), nullable=False),
        sa.Column("previous_values", sa.JSON(), nullable=False),
        sa.Column("new_values", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("problem_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_problem_revisions_problem_id"), ["problem_id"], unique=False
        )

    op.create_table(
        "problem_score_breakdowns",
        sa.Column("problem_id", sa.Integer(), nullable=False),
        sa.Column("criterion", sa.String(length=50), nullable=False),
        sa.Column("analysis", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problems.id"],
        ),
        sa.PrimaryKeyConstraint("problem_id", "criterion"),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("problem_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("hidden", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_questions_problem_id"), ["problem_id"], unique=False
        )

    op.create_table(
        "submissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("problem_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("solution_description", sa.Text(), nullable=False),
        sa.Column("implementation_details", sa.Text(), nullable=False),
        sa.Column("demo_url", sa.String(length=1000), nullable=False),
        sa.Column("repository_url", sa.String(length=1000), nullable=False),
        sa.Column("project_file_name", sa.String(length=180), nullable=False),
        sa.Column("anonymous_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("hidden", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('SUBMITTED','WINNER','NOT_SELECTED')"),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "problem_id", "anonymous_number", name="uq_anonymous_number"
        ),
        sa.UniqueConstraint("problem_id", "team_id", name="uq_problem_team"),
    )
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_submissions_problem_id"), ["problem_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_submissions_team_id"), ["team_id"], unique=False
        )
        batch_op.create_index(
            "uq_one_winner_per_problem",
            ["problem_id"],
            unique=True,
            postgresql_where=sa.text("status = 'WINNER'"),
            sqlite_where=sa.text("status = 'WINNER'"),
        )

    op.create_table(
        "answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("hidden", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_answers_question_id"), ["question_id"], unique=False
        )

    op.create_table(
        "points_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("problem_id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("points", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reason", sa.String(length=180), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("points >= 0"),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id", "problem_id", name="uq_points_once"),
    )
    with op.batch_alter_table("points_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_points_transactions_student_id"),
            ["student_id"],
            unique=False,
        )

    op.create_table(
        "submission_ai_reviews",
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("analysis", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
        ),
        sa.PrimaryKeyConstraint("submission_id"),
    )
    op.create_table(
        "submission_chats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id"),
    )
    op.create_table(
        "submission_members",
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
        ),
        sa.PrimaryKeyConstraint("submission_id", "student_id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("sender_type", sa.String(length=10), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["submission_chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_messages_chat_id"), ["chat_id"], unique=False
        )

    # use_alter breaks the Problem/Submission cycle; PostgreSQL needs the FK added
    # explicitly after both tables exist. SQLite includes it in CREATE TABLE.
    if op.get_bind().dialect.name == "postgresql":
        op.create_foreign_key(
            "fk_problem_winner",
            "problems",
            "submissions",
            ["winner_submission_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.drop_constraint("fk_problem_winner", "problems", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_chat_id"))

    op.drop_table("messages")
    op.drop_table("submission_members")
    op.drop_table("submission_chats")
    op.drop_table("submission_ai_reviews")
    with op.batch_alter_table("points_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_points_transactions_student_id"))

    op.drop_table("points_transactions")
    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_answers_question_id"))

    op.drop_table("answers")
    with op.batch_alter_table("submissions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_one_winner_per_problem",
            postgresql_where=sa.text("status = 'WINNER'"),
            sqlite_where=sa.text("status = 'WINNER'"),
        )
        batch_op.drop_index(batch_op.f("ix_submissions_team_id"))
        batch_op.drop_index(batch_op.f("ix_submissions_problem_id"))

    op.drop_table("submissions")
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_questions_problem_id"))

    op.drop_table("questions")
    op.drop_table("problem_score_breakdowns")
    with op.batch_alter_table("problem_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_problem_revisions_problem_id"))

    op.drop_table("problem_revisions")
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comments_problem_id"))

    op.drop_table("comments")
    op.drop_table("team_members")
    with op.batch_alter_table("problems", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_problems_quality_score"))
        batch_op.drop_index(batch_op.f("ix_problems_deadline"))
        batch_op.drop_index(batch_op.f("ix_problems_company_id"))

    op.drop_table("problems")
    op.drop_table("student_profiles")
    op.drop_table("demo_sessions")
    op.drop_table("companies")
    op.drop_table("users")
    op.drop_table("teams")
    with op.batch_alter_table("moderation_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_moderation_items_status"))

    op.drop_table("moderation_items")
    # ### end Alembic commands ###
